package dev.sszperling.pushy

const val UUID_PLACEHOLDER = "<Auto-generated UUID>"

enum class Preset {
	FCM {
		override val action = "com.google.android.c2dm.intent.RECEIVE"
		override val defaultExtras = mapOf(
			"google.message_id" to UUID_PLACEHOLDER,
			"gcm.n.e" to "1",
		)
		override val requiredExtras = listOf("gcm.n.title")
	},
	Custom {
		override val action = ""
		override val defaultExtras = mapOf<String, String>()
		override val requiredExtras = listOf<String>()
	},
	;

	abstract val action: String
	abstract val defaultExtras: Map<String, String>
	abstract val requiredExtras: List<String>
}

data class Extra(val key: String = "key", val value: String = "value")
